### ISSUE TITLE
Schematica printer doesn't work without using /sit command

### ISSUE THREAD

**Issue by SaltyAlpha** [SaltyAlpha/Grim#1003]
> [!NOTE]
> Imported issue from `GrimAnticheat/Grim#1001`.
> Original author: `StKillReal`; created: `2023-03-22T07:20:08Z`; updated: `2023-03-24T16:53:22Z`.
> Original state: `closed`; assignees: none; milestone: none.
> Original URL: `https://github.com/GrimAnticheat/Grim/issues/1001`.

### Describe the false positive and how to replicate it

I want to allow players use Printer to build arts, but permissions doesn't help. Now they can build using printer only when they sit using Gsit plugin. Grim ac works better then all anticheats I used before, but only with grim I can't just disable some checks for players.
1) Try to build something using SchematicaPriner
![image](https://user-images.githubusercontent.com/60330193/226828736-d777e0b1-ec18-4563-a1fe-1b8337113f61.png)
![2023-03-22_10 16 42](https://user-images.githubusercontent.com/60330193/226828833-bb5d3ab5-4163-4b42-a488-26dd720b47c0.png)

### Grim version

2.3.39

### Server version

![image](https://user-images.githubusercontent.com/60330193/226828943-dac68566-23b8-4eb7-a2cc-7a101a30d2d1.png)

### Plugins

![image](https://user-images.githubusercontent.com/60330193/226829002-c4e8c0ed-56b8-4154-859a-68c56e5911bc.png)

**Comment by SaltyAlpha** [comment]
## Imported discussion

> Original conversation comment by `noiverre` at `2023-03-24T04:34:23Z`.

Saw other issue related to Bedrock checks, this line doesn't appear in the console

[09:58:02 INFO]: [floodgate] Floodgate player logged in as .Define_Outside joined (UUID: 00000000-0000-0000-0009-01f7ed6f3737)
[09:58:03 INFO]: .Define_Outside joined the game
[09:58:03 INFO]: .Define_Outside[/123.456.789.123:0] logged in with entity id 128 at ([world]-2.5, 101.0, 3.5)
> [09:58:20 INFO]: This player is exempt from all checks!
> [09:58:20 INFO]: User connection state: PLAY

---

> Original conversation comment by `MachineBreaker` at `2023-03-24T09:33:27Z`.

Did you configured correctly Floodgate?

---

> Original conversation comment by `noiverre` at `2023-03-24T09:38:21Z`.

```yaml
remote:
  # The IP address of the remote (Java Edition) server
  # If it is "auto", for standalone version the remote address will be set to 127.0.0.1,
  # for plugin versions, it is recommended to keep this as "auto" so Geyser will automatically configure address, port, and auth-type.
  # Leave as "auto" if floodgate is installed.
  address: auto
  # The port of the remote (Java Edition) server
  # For plugin versions, if address has been set to "auto", the port will also follow the server's listening port.
  port: 25560
  # Authentication type. Can be offline, online, or floodgate (see https://github[.]com/GeyserMC/Geyser/wiki/Floodgate).
  # For plugin versions, it's recommended to keep the `address` field to "auto" so Floodgate support is automatically configured.
  # If Floodgate is installed and `address:` is set to "auto", then "auth-type: floodgate" will automatically be used.
  auth-type: floodgate
  # Allow for password-based authentication methods through Geyser. Only useful in online mode.
  # If this is false, users must authenticate to Microsoft using a code provided by Geyser on their desktop.
  allow-password-authentication: true
  # Whether to enable PROXY protocol or not while connecting to the server.
  # This is useful only when:
  # 1) Your server supports PROXY protocol (it probably doesn't)
  # 2) You run Velocity or BungeeCord with the option enabled in the proxy's main config.
  # IF YOU DON'T KNOW WHAT THIS IS, DON'T TOUCH IT!
  use-proxy-protocol: false
  # Forward the hostname that the Bedrock client used to connect over to the Java server
  # This is designed to be used for forced hosts on proxies
  forward-hostname: false
```

---

> Original conversation comment by `noiverre` at `2023-03-24T09:51:14Z`.

Should I remove floodgate in Velocity and use floodgate in backend only? the key.pem has different value

---

> Original conversation comment by `MachineBreaker` at `2023-03-24T10:14:23Z`.

> Should I remove floodgate in Velocity and use floodgate in backend only? the key.pem has different value

Afaik you need to have the same key Proxy <-> Backend

---

> Original conversation comment by `noiverre` at `2023-03-24T10:17:04Z`.

I set up the same key.pem by copying it both in Velocity and backend, it's still checking on Geyser players

---

> Original conversation comment by `MWHunter` at `2023-03-24T13:53:40Z`.

https://github[.]com/GeyserMC/Geyser/wiki/Floodgate/f4fa39c2b1f9517af7da0c7729b1ad709a688a45#running-floodgate-on-spigot-servers-behind-bungeecord-or-velocity

---

> Original conversation comment by `noiverre` at `2023-03-24T20:49:29Z`.

Looks like I misconfigured Geyser. My player-info-forwarding is modern whereas it's required to use LEGACY

Haven't tested it yet, will give update after I test this

---

> Original conversation comment by `noiverre` at `2023-03-25T03:38:05Z`.

I followed the tutorial above, here's the result using LEGACY forwarding

On backend
![image](https://user-images.githubusercontent.com/77881970/227690445-95c6c869-41fa-4ca3-9853-afa080e487fa.png)


On velocity
![image](https://user-images.githubusercontent.com/77881970/227690424-2cab282f-de79-4e24-b1cd-69457273f5ab.png)


I also enabled `send-floodgate-data` to true in floodgate config in Velocity

There's no this line
> INFO]: This player is exempt from all checks!
> INFO]: User connection state: PLAY

However, the user isn't stuck anymore by bad packets check etc, it works fine

Then, I tried to use MODERN forwarding, but keeping `send-floodgate-data` to true

It also works, I guess this is an issue from Geyser?

---

> Original conversation comment by `MWHunter` at `2023-03-26T17:21:10Z`.

If the player is exempt from all checks that means they bedrock - since grim isn't designed for bedrock users

---
